# Generated by Django 3.1.1 on 2020-10-02 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=16, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=500)),
                ('quiz_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qa.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=200)),
                ('is_answer', models.BooleanField(default=False)),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='qa.question')),
            ],
        ),
    ]
