# Generated by Django 3.1.2 on 2020-10-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20200930_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='room_id',
            field=models.CharField(max_length=16),
        ),
    ]
